language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"

install:
    - pip install tox
    - pip install coveralls

script: tox

after_success:
    - coveralls
